using FHSMS.Application.Common.Interfaces;
using FHSMS.Application.Common.Models;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace FHSMS.Application.Invoices.Queries.GetInvoices;

public class GetInvoicesQueryHandler : IRequestHandler<GetInvoicesQuery, List<InvoiceDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly ICurrentUserService _currentUser;

    public GetInvoicesQueryHandler(IApplicationDbContext context, ICurrentUserService currentUser)
    {
        _context = context;
        _currentUser = currentUser;
    }

    public async Task<List<InvoiceDto>> Handle(GetInvoicesQuery request, CancellationToken cancellationToken)
    {
        var query = _context.Invoices.Include(i => i.Items).AsQueryable();

        // Role-based access, mirroring GetFarmerInvoicesQueryHandler on the
        // buying side - "agents only must see their invoices generated by
        // their role":
        //   SuperAdmin, Driver -> everything (reports/reconciliation need the full picture)
        //   HotelAgent         -> only invoices for orders THEY placed
        //   FarmerAgent        -> none (this is the selling side, not their role - see FarmerInvoicesController for theirs)
        // Note: HotelCustomer/PublicPortalUser are intentionally left
        // unrestricted here for now - there is no User<->Customer link in
        // this codebase yet to scope "their own" invoices correctly, and
        // guessing at one risks silently breaking self-checkout. Flagging
        // this as a follow-up rather than a change made here.
        switch (_currentUser.Role)
        {
            case "HotelAgent" when _currentUser.UserId is { } hotelAgentId:
                var myOrderIds = await _context.Orders
                    .Where(o => o.AgentUserId == hotelAgentId)
                    .Select(o => o.Id)
                    .ToListAsync(cancellationToken);
                query = query.Where(i => myOrderIds.Contains(i.OrderId));
                break;
            case "FarmerAgent":
                return new List<InvoiceDto>();
        }

        if (request.CustomerId is { } customerId)
            query = query.Where(i => i.CustomerId == customerId);

        if (request.Status is { } status)
            query = query.Where(i => i.Status == status);

        var invoices = await query.OrderByDescending(i => i.InvoiceDate).ToListAsync(cancellationToken);

        return invoices.Select(invoice => new InvoiceDto
        {
            Id = invoice.Id,
            InvoiceNumber = invoice.InvoiceNumber,
            OrderId = invoice.OrderId,
            CustomerId = invoice.CustomerId,
            InvoiceDate = invoice.InvoiceDate,
            Status = invoice.Status,
            TaxWasEnabled = invoice.TaxWasEnabled,
            TaxMode = invoice.TaxMode,
            Subtotal = invoice.Subtotal,
            TaxableAmount = invoice.TaxableAmount,
            TaxAmount = invoice.TaxAmount,
            Discount = invoice.Discount,
            PlatformCommissionRateApplied = invoice.PlatformCommissionRateApplied,
            PlatformCommissionAmount = invoice.PlatformCommissionAmount,
            HotelAgentBonusAmount = invoice.HotelAgentBonusAmount,
            GrandTotal = invoice.GrandTotal,
            AmountPaid = invoice.AmountPaid,
            BalanceDue = invoice.BalanceDue,
            Items = invoice.Items.Select(i => new InvoiceItemDto
            {
                ProductId = i.ProductId,
                ProductName = i.ProductName,
                Quantity = i.Quantity,
                UnitPrice = i.UnitPrice,
                LineSubtotal = i.LineSubtotal,
                TaxProfileApplied = i.TaxProfileApplied,
                TaxRateApplied = i.TaxRateApplied,
                TaxableAmount = i.TaxableAmount,
                TaxAmount = i.TaxAmount,
                LineTotal = i.LineTotal
            }).ToList()
        }).ToList();
    }
}
