using FHSMS.Domain.Common;
using FHSMS.Domain.Enums;
using FHSMS.Domain.Exceptions;

namespace FHSMS.Domain.Entities;

/// <summary>
/// The buying-side counterpart to Invoice: what the company owes a farmer
/// for a specific stock receipt. Auto-generated by
/// RecordInventoryTransactionCommandHandler the instant a Receiving
/// transaction is logged - TotalAmount = Quantity x the product's buying
/// price AT THAT MOMENT (see Product.GetBuyingPriceAsOf), frozen here exactly
/// like a hotel-side invoice freezes its tax rate, so a later buying-price
/// change never rewrites an already-generated farmer invoice.
///
/// Exactly one FarmerInvoice exists per InventoryTransaction - enforced both
/// by a unique DB index (InventoryTransactionConfiguration) and structurally,
/// since both are created together inside a single handler call - so there is
/// no code path that can generate this twice for the same stock-in.
/// </summary>
public class FarmerInvoice : AuditableEntity
{
    public string InvoiceNumber { get; private set; } = default!;
    public Guid InventoryTransactionId { get; private set; }
    public Guid ProductId { get; private set; }
    public Guid? FarmerId { get; private set; }
    public Guid? AgentUserId { get; private set; }

    public decimal Quantity { get; private set; }
    /// <summary>The product's buying price as of the moment this stock was logged - frozen, never recalculated even if Admin changes the buying price later.</summary>
    public decimal BuyingPriceApplied { get; private set; }
    /// <summary>Quantity x BuyingPriceApplied - what the company owes the farmer for this batch.</summary>
    public decimal TotalAmount { get; private set; }

    public FarmerInvoiceStatus Status { get; private set; }
    public Guid? ApprovedByUserId { get; private set; }
    public DateTime? ApprovedAt { get; private set; }

    private FarmerInvoice() { } // EF Core

    /// <summary>
    /// isPreApproved mirrors InventoryTransaction.IsConfirmed's own rule: a
    /// SuperAdmin's own stock-in is auto-confirmed (no one else needs to
    /// double-check the admin's own count), so their FarmerInvoice is created
    /// already Approved. A farmer agent's stock-in starts PendingApproval and
    /// only becomes Approved when an admin confirms the receipt.
    /// </summary>
    public static FarmerInvoice Create(
        string invoiceNumber, Guid inventoryTransactionId, Guid productId, Guid? farmerId, Guid? agentUserId,
        decimal quantity, decimal buyingPriceApplied, bool isPreApproved, Guid? approvedByUserId)
    {
        if (quantity <= 0)
            throw new DomainException("Quantity must be greater than zero.");
        if (buyingPriceApplied < 0)
            throw new DomainException("Buying price cannot be negative.");

        return new FarmerInvoice
        {
            InvoiceNumber = invoiceNumber,
            InventoryTransactionId = inventoryTransactionId,
            ProductId = productId,
            FarmerId = farmerId,
            AgentUserId = agentUserId,
            Quantity = quantity,
            BuyingPriceApplied = buyingPriceApplied,
            TotalAmount = Math.Round(quantity * buyingPriceApplied, 2),
            Status = isPreApproved ? FarmerInvoiceStatus.Approved : FarmerInvoiceStatus.PendingApproval,
            ApprovedByUserId = isPreApproved ? approvedByUserId : null,
            ApprovedAt = isPreApproved ? DateTime.UtcNow : null
        };
    }

    /// <summary>Admin confirms the stock actually arrived - the amount owed to the farmer becomes final, matching ConfirmStockReceiptCommand.</summary>
    public void Approve(Guid approvedByUserId)
    {
        if (Status == FarmerInvoiceStatus.Approved)
            throw new DomainException("This farmer invoice has already been approved.");

        Status = FarmerInvoiceStatus.Approved;
        ApprovedByUserId = approvedByUserId;
        ApprovedAt = DateTime.UtcNow;
    }
}
