using FHSMS.Application.Common.Interfaces;
using FHSMS.Application.Common.Models;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace FHSMS.Application.FarmerInvoices.Queries.GetFarmerInvoices;

public class GetFarmerInvoicesQueryHandler : IRequestHandler<GetFarmerInvoicesQuery, List<FarmerInvoiceDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly ICurrentUserService _currentUser;

    public GetFarmerInvoicesQueryHandler(IApplicationDbContext context, ICurrentUserService currentUser)
    {
        _context = context;
        _currentUser = currentUser;
    }

    public async Task<List<FarmerInvoiceDto>> Handle(GetFarmerInvoicesQuery request, CancellationToken cancellationToken)
    {
        var query = _context.FarmerInvoices.AsQueryable();

        // A farmer agent only ever sees invoices generated by their own
        // stock-ins - "agents only must see their invoices generated by
        // their role" - regardless of any FarmerId filter they pass.
        // SuperAdmin and Driver see across all agents.
        if (_currentUser.Role == "FarmerAgent" && _currentUser.UserId is { } agentUserId)
            query = query.Where(f => f.AgentUserId == agentUserId);

        if (request.FarmerId is { } farmerId)
            query = query.Where(f => f.FarmerId == farmerId);

        if (request.Status is { } status)
            query = query.Where(f => f.Status == status);

        var invoices = await query.OrderByDescending(f => f.CreatedAt).ToListAsync(cancellationToken);

        var productIds = invoices.Select(f => f.ProductId).Distinct().ToList();
        var products = await _context.Products.Include(p => p.Unit)
            .Where(p => productIds.Contains(p.Id)).ToDictionaryAsync(p => p.Id, cancellationToken);

        var farmerIds = invoices.Where(f => f.FarmerId != null).Select(f => f.FarmerId!.Value).Distinct().ToList();
        var farmers = await _context.Farmers.Where(f => farmerIds.Contains(f.Id)).ToDictionaryAsync(f => f.Id, cancellationToken);

        var agentIds = invoices.Where(f => f.AgentUserId != null).Select(f => f.AgentUserId!.Value).Distinct().ToList();
        var agents = await _context.Users.Where(u => agentIds.Contains(u.Id)).ToDictionaryAsync(u => u.Id, cancellationToken);

        return invoices.Select(f => new FarmerInvoiceDto
        {
            Id = f.Id,
            InvoiceNumber = f.InvoiceNumber,
            InventoryTransactionId = f.InventoryTransactionId,
            ProductId = f.ProductId,
            ProductName = products.TryGetValue(f.ProductId, out var p) ? p.Name : null,
            UnitAbbreviation = products.TryGetValue(f.ProductId, out var pu) ? pu.Unit?.Abbreviation : null,
            FarmerId = f.FarmerId,
            FarmerName = f.FarmerId != null && farmers.TryGetValue(f.FarmerId.Value, out var fm) ? fm.Name : null,
            AgentUserId = f.AgentUserId,
            AgentName = f.AgentUserId != null && agents.TryGetValue(f.AgentUserId.Value, out var a) ? a.FullName : null,
            Quantity = f.Quantity,
            BuyingPriceApplied = f.BuyingPriceApplied,
            TotalAmount = f.TotalAmount,
            Status = f.Status,
            CreatedAt = f.CreatedAt,
            ApprovedAt = f.ApprovedAt
        }).ToList();
    }
}
